multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://mysql/shivitco_super_admin?allowPublicKeyRetrieval=true&useSSL=false
#        url: jdbc:mysql://superadmin.cmswbwygi97w.us-east-1.rds.amazonaws.com:3306/shivit_super_admin?allowPublicKeyRetrieval=true&useSSL=false
#        username: admin
#        password: mysql123
        #url: jdbc:mysql://localhost:3306/albinosh_super_admin?allowPublicKeyRetrieval=true&useSSL=false
        username: shivitco_superadmin
        password: 4?ip$DcUS+F;
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
        
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
    - https://albino.shivit.co.in/oauth2/redirect
logging:
  level:
    org:
      springframework: debug